// Garamon unit tests
// CliffordReference.hpp
//
// Licence MIT
//
// A naive, independent implementation of a Clifford (geometric) algebra, used as a reference to check the
// libraries generated by Garamon. It favours simplicity over speed:
//  - a multivector is a dense array of 2^n coefficients indexed by the "xor index" (bitmask) of the basis blades,
//    which is also the indexing used by the generated libraries (mv[E12] == mv[0b011]),
//  - the basis blades are the outer products of the basis vectors in increasing index order (e.g. e13 = e1^e3),
//    whatever the metric, as in the generated libraries,
//  - the metric is any symmetric bilinear form B (possibly non-diagonal and/or degenerate),
//  - the geometric product of basis blades is computed with the recursion
//        e_i * M         = e_i _| M + e_i ^ M                 (for a basis vector e_i)
//        (e_i ^ R) * M   = e_i * (R * M) - (e_i _| R) * M     (e_i ^ R = e_i R - e_i _| R)
//    which only requires the outer product and the left contraction of a vector onto a blade:
//        e_i _| (b_1 ^ ... ^ b_k) = sum_j (-1)^{j-1} B(e_i, b_j) b_1 ^ ... ^ (no b_j) ^ ... ^ b_k
//  - the other products are defined from the geometric product by grade selection.

#ifndef GARAMON_TESTS_CLIFFORD_REFERENCE_HPP
#define GARAMON_TESTS_CLIFFORD_REFERENCE_HPP

#include <bitset>
#include <cmath>
#include <cstdlib>
#include <stdexcept>
#include <string>
#include <vector>

namespace garamon_test {

class CliffordReference {
public:
    /// dense multivector: coefficient of the basis blade whose bitmask is i
    using Mv = std::vector<double>;

    explicit CliffordReference(const std::vector<std::vector<double>> &bilinearForm)
        : metric(bilinearForm), n((unsigned int)bilinearForm.size()) {
        if(n == 0 || n > 10)
            throw std::invalid_argument("CliffordReference: dimension should be in [1,10]");
        for(const auto &row : metric)
            if(row.size() != n)
                throw std::invalid_argument("CliffordReference: the metric should be a square matrix");
        memo.resize(size() * size());
        computed.assign(size() * size(), false);
    }

    unsigned int dimension() const { return n; }
    unsigned int size() const { return 1u << n; }
    unsigned int pseudoScalarIndex() const { return size() - 1; }

    static unsigned int grade(const unsigned int bitmask) { return (unsigned int)std::bitset<32>(bitmask).count(); }

    Mv zero() const { return Mv(size(), 0.0); }

    Mv blade(const unsigned int bitmask, const double coefficient = 1.0) const {
        Mv mv = zero();
        mv[bitmask] = coefficient;
        return mv;
    }

    Mv scalar(const double value) const { return blade(0, value); }

    /// geometric product of two basis blades (memoised)
    const Mv &bladeProduct(const unsigned int a, const unsigned int b) const {
        const std::size_t key = (std::size_t)a * size() + b;
        if(!computed[key]) {
            memo[key] = computeBladeProduct(a, b);
            computed[key] = true;
        }
        return memo[key];
    }

    // ------------------------------------------------------------------ products

    /// geometric product
    Mv geometric(const Mv &x, const Mv &y) const {
        return bilinear(x, y, [](unsigned int, unsigned int, unsigned int) { return true; });
    }

    /// outer product: grade (r+s) part of the product of an r-blade with an s-blade
    Mv outer(const Mv &x, const Mv &y) const {
        return bilinear(x, y, [](unsigned int r, unsigned int s, unsigned int k) { return k == r + s; });
    }

    /// left contraction (garamon: mv1 < mv2): grade (s-r) part when r <= s, else 0
    Mv leftContraction(const Mv &x, const Mv &y) const {
        return bilinear(x, y, [](unsigned int r, unsigned int s, unsigned int k) { return r <= s && k == s - r; });
    }

    /// right contraction (garamon: mv1 > mv2): grade (r-s) part when r >= s, else 0
    Mv rightContraction(const Mv &x, const Mv &y) const {
        return bilinear(x, y, [](unsigned int r, unsigned int s, unsigned int k) { return r >= s && k == r - s; });
    }

    /// Hestenes inner product (garamon: mv1 | mv2): grade |r-s| part, 0 when one of the operands is a scalar
    Mv inner(const Mv &x, const Mv &y) const {
        return bilinear(x, y, [](unsigned int r, unsigned int s, unsigned int k) { return r != 0 && s != 0 && k == absDiff(r, s); });
    }

    /// dot product (garamon: mv1.dotProduct(mv2)): grade |r-s| part, including the scalars
    Mv dot(const Mv &x, const Mv &y) const {
        return bilinear(x, y, [](unsigned int r, unsigned int s, unsigned int k) { return k == absDiff(r, s); });
    }

    /// scalar product (garamon: mv1.scalarProduct(mv2)): sum of the scalar parts of the products of same-grade components
    Mv scalarProduct(const Mv &x, const Mv &y) const {
        return bilinear(x, y, [](unsigned int r, unsigned int s, unsigned int k) { return r == s && k == 0; });
    }

    // ------------------------------------------------------------------ unary operations

    Mv reverse(const Mv &x) const {
        Mv result(x);
        for(unsigned int i = 0; i < size(); ++i) {
            const unsigned int k = grade(i);
            if(((k * (k - (k > 0 ? 1 : 0))) / 2) % 2 == 1)
                result[i] = -result[i];
        }
        return result;
    }

    Mv gradePart(const Mv &x, const unsigned int k) const {
        Mv result = zero();
        for(unsigned int i = 0; i < size(); ++i)
            if(grade(i) == k)
                result[i] = x[i];
        return result;
    }

    /// pseudo-scalar I = e1^e2^...^en
    Mv pseudoScalar() const { return blade(pseudoScalarIndex()); }

    /// right complement: the multivector comp(A) such that A ^ comp(A) = I for each basis blade A
    Mv rightComplement(const Mv &x) const {
        Mv result = zero();
        for(unsigned int i = 0; i < size(); ++i) {
            if(x[i] == 0.0)
                continue;
            const unsigned int complement = pseudoScalarIndex() ^ i;
            result[complement] += outerSign(i, complement) * x[i];
        }
        return result;
    }

    /// sign of the outer product of the basis blades a and b (assuming a & b == 0)
    static double outerSign(const unsigned int a, const unsigned int b) {
        // count the number of transpositions to sort the concatenation of a and b
        unsigned int swaps = 0;
        for(unsigned int i = 0; i < 32; ++i)
            if(a & (1u << i))
                swaps += grade(b & ((1u << i) - 1u)); // elements of b smaller than i must cross the element i of a
        return (swaps % 2 == 0) ? 1.0 : -1.0;
    }

    // ------------------------------------------------------------------ linear algebra helpers

    static Mv add(const Mv &x, const Mv &y) {
        Mv result(x);
        for(std::size_t i = 0; i < y.size(); ++i)
            result[i] += y[i];
        return result;
    }

    static Mv sub(const Mv &x, const Mv &y) {
        Mv result(x);
        for(std::size_t i = 0; i < y.size(); ++i)
            result[i] -= y[i];
        return result;
    }

    static Mv scale(const Mv &x, const double s) {
        Mv result(x);
        for(double &value : result)
            value *= s;
        return result;
    }

    static double maxAbs(const Mv &x) {
        double m = 0.0;
        for(double value : x)
            m = std::fmax(m, std::fabs(value));
        return m;
    }

    static double maxAbsDiff(const Mv &x, const Mv &y) { return maxAbs(sub(x, y)); }

    bool isNull(const Mv &x, const double tolerance = 1.0e-12) const { return maxAbs(x) <= tolerance; }

private:
    std::vector<std::vector<double>> metric;
    unsigned int n;
    mutable std::vector<Mv> memo;
    mutable std::vector<bool> computed;

    static unsigned int absDiff(const unsigned int a, const unsigned int b) { return a > b ? a - b : b - a; }

    // bilinear extension of a blade product, keeping only the grades k selected by keep(r, s, k)
    template<typename Selector>
    Mv bilinear(const Mv &x, const Mv &y, Selector keep) const {
        Mv result = zero();
        for(unsigned int a = 0; a < size(); ++a) {
            if(x[a] == 0.0)
                continue;
            for(unsigned int b = 0; b < size(); ++b) {
                if(y[b] == 0.0)
                    continue;
                const Mv &product = bladeProduct(a, b);
                const double coefficient = x[a] * y[b];
                for(unsigned int c = 0; c < size(); ++c)
                    if(product[c] != 0.0 && keep(grade(a), grade(b), grade(c)))
                        result[c] += coefficient * product[c];
            }
        }
        return result;
    }

    // e_i ^ e_C
    void vectorOuterBlade(const unsigned int i, const unsigned int c, const double coefficient, Mv &result) const {
        const unsigned int bit = 1u << i;
        if(c & bit)
            return;
        result[c | bit] += outerSign(bit, c) * coefficient;
    }

    // e_i _| e_C
    void vectorContractBlade(const unsigned int i, const unsigned int c, const double coefficient, Mv &result) const {
        int position = 0; // position of e_j in the blade e_C (increasing index order)
        for(unsigned int j = 0; j < n; ++j) {
            const unsigned int bit = 1u << j;
            if(!(c & bit))
                continue;
            if(metric[i][j] != 0.0)
                result[c ^ bit] += ((position % 2 == 0) ? 1.0 : -1.0) * metric[i][j] * coefficient;
            ++position;
        }
    }

    // e_i * M, for any multivector M
    Mv vectorProduct(const unsigned int i, const Mv &m) const {
        Mv result = zero();
        for(unsigned int c = 0; c < size(); ++c) {
            if(m[c] == 0.0)
                continue;
            vectorContractBlade(i, c, m[c], result);
            vectorOuterBlade(i, c, m[c], result);
        }
        return result;
    }

    Mv computeBladeProduct(const unsigned int a, const unsigned int b) const {

        // 1 * e_B = e_B
        if(a == 0)
            return blade(b);

        // e_A = e_i ^ e_R where e_i is the basis vector of lowest index of e_A
        unsigned int i = 0;
        while(!(a & (1u << i)))
            ++i;
        const unsigned int r = a ^ (1u << i);

        // e_A * e_B = e_i * (e_R * e_B) - (e_i _| e_R) * e_B
        Mv result = vectorProduct(i, bladeProduct(r, b));

        Mv contraction = zero();
        vectorContractBlade(i, r, 1.0, contraction);
        for(unsigned int c = 0; c < size(); ++c) {
            if(contraction[c] == 0.0)
                continue;
            const Mv &product = bladeProduct(c, b);
            for(unsigned int k = 0; k < size(); ++k)
                result[k] -= contraction[c] * product[k];
        }

        return result;
    }
};

} // namespace garamon_test

#endif // GARAMON_TESTS_CLIFFORD_REFERENCE_HPP
